const hobbies = [
    "Amateur radio",
    "Audiophilia",
    "Aquarium keeping",
    "Baking",
    "Bonsai",
    "Computer programming",
    "Cooking",
    "Creative writing",
    "Dance",
    "Drawing",
    "Basketball",
    "Gardening",
    "Genealogy",
    "Jewelry making",
    "Knapping",
    "Lapidary",
    "Locksport",
    "Musical instruments",
    "Painting",
    "Knitting",
    "Scrapbooking",
    "Sculpting",
    "Sewing",
    "Singing",
    "Watching movies",
    "Watching television",
    "Woodworking",
    "Air sports",
    "Board sports",
    "Cycling",
    "Freerunning",
    "Hunting",
    "Jogging",
    "Kayaking",
    "Motor sports",
    "Mountain biking",
    "Parkour",
    "Playing with a pet",
    "Photography",
    "Rock climbing",
    "Running",
    "Sailing",
    "Sand castle building",
    "Sculling",
    "Rowing",
    "Surfing",
    "Swimming",
    "Tai chi chuan",
    "Vehicle restoration",
    "Water sports",
    "Yoga",
    "Antiquing",
    "Art collecting",
    "Coin collecting",
    "Element collecting",
    "Stamp collecting",
    "Vintage books",
    "Vintage clothing",
    "Record collecting",
    "Trading Cards collecting",
    "Antiquities",
    "Auto audiophilia",
    "Fossil",
    "Insect",
    "Leaf",
    "Metal detecting",
    "Mineral",
    "Petal",
    "Rock",
    "Seaglass",
    "Seashell",
    "Wrestling",
    "Bowling",
    "Boxing",
    "Chess",
    "Cheerleading",
    "Cubing",
    "Bridge",
    "Billiards",
    "Darts",
    "Fencing",
    "Gaming",
    "Handball",
    "Martial arts",
    "Table football",
    "Airsoft",
    "American football",
    "Archery",
    "Association football",
    "Auto racing",
    "Badminton",
    "Baseball",
    "Basketball",
    "Climbing",
    "Cricket",
    "Cycling",
    "Disc golf",
    "Equestrianism",
    "Figure skating",
    "Fishing",
    "Foot-bag",
    "Golfing",
    "Gymnastics",
    "Ice hockey",
    "Kart racing",
    "Netball",
    "Paintball",
    "Racquetball",
    "Rugby league football",
    "Running",
    "Shooting",
    "Squash",
    "Surfing",
    "Swimming",
    "Table tennis",
    "Tennis",
    "Volleyball",
    "Microscopy",
    "Reading",
    "Shortwave radios",
    "Amateur geology",
    "Bird watching",
    "College football",
    "Geocaching",
    "Meteorology",
    "Parkour",
    "People watching",
    "Travel"
]

export default function random_hobby():string {
    return hobbies[Math.floor(Math.random() * hobbies.length)];
}